# Production Docker Compose for Dell Linux Server Deployment
# Simplified deployment focused on core functionality

version: '3.8'

services:
  # Main Stripe Dashboard application
  stripe-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
      target: production
    container_name: stripe-dashboard-app
    restart: unless-stopped
    
    # Environment configuration
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - DATABASE_URL=sqlite:////app/production.db
      - HOST=0.0.0.0
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Hong_Kong
    
    # Volume mounts for persistence
    volumes:
      - stripe_csv_data:/app/csv_data
      - stripe_uploads:/app/uploads
      - stripe_logs:/app/logs
    
    # Network configuration
    networks:
      - stripe_network
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx reverse proxy for production
  nginx:
    image: nginx:1.25-alpine
    container_name: stripe-dashboard-nginx
    restart: unless-stopped
    
    ports:
      - "8081:80"
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    
    depends_on:
      stripe-dashboard:
        condition: service_healthy
    
    networks:
      - stripe_network
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: stripe-dashboard-redis
    restart: unless-stopped
    
    command: redis-server --appendonly yes
    
    volumes:
      - redis_data:/data
    
    networks:
      - stripe_network
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

# Network configuration
networks:
  stripe_network:
    driver: bridge

# Volume definitions for data persistence
volumes:
  stripe_csv_data:
    driver: local
  
  stripe_uploads:
    driver: local
  
  stripe_logs:
    driver: local
  
  redis_data:
    driver: local